name: inspection
description: validation form inputs and data in Dart & Flutter like Laravel framework
version: 0.0.13
homepage: https://github.com/novaday-co/inspection

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: